name: "DEST_BRANCH check"

on:
- pull_request_target

permissions:
  contents: read

jobs:
  check_dest_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get_dest_branch
      uses: mikefarah/yq@master
      with:
        cmd: yq '.env.DEST_BRANCH' .cirrus.yml
    - if: ${{ steps.get_dest_branch.outputs.result != github.ref_name }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('DEST_BRANCH is not set to the branch name in .cirrus')
